---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.kubedoop.dev
  resources:
  - authenticationclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.kubedoop.dev
  resources:
  - s3buckets
  - s3connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spark.kubedoop.dev
  resources:
  - sparkhistoryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spark.kubedoop.dev
  resources:
  - sparkhistoryservers/finalizers
  verbs:
  - update
- apiGroups:
  - spark.kubedoop.dev
  resources:
  - sparkhistoryservers/status
  verbs:
  - get
  - patch
  - update
