apiVersion: spark.kubedoop.dev/v1alpha1
kind: SparkHistoryServer
metadata:
  labels:
    app.kubernetes.io/name: sparkhistoryserver
    app.kubernetes.io/instance: sparkhistoryserver
    app.kubernetes.io/part-of: spark-k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-k8s-operator
  name: sparkhistoryserver-sample
spec:
  clusterOperation:
    stopped: false
  clusterConfig:
    logFileDirectory:
      s3:
        bucket:
          inline:
            bucketName: spark-k8s
            connection:
              inline:
                credentials:
                  secretClass: spark-s3
  node:
    config:
      resources:
        cpu:
          min: 100m
          max: 200m
        memory:
          limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          gracefulShutdownTimeout: 10s
          logging:
            containers:
              node:
                console:
                  level: "INFO"
          resources:
            cpu:
              min: 300m
              max: 400m
            memory:
              limit: 612Mi
